services:
  app:
    build:
      context: ./
      dockerfile: DockerFile
    container_name: myphp
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www/


  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: ngin_php
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d